package moduloAjuda;

public class AjudaTexto {
	
	private String textoNavegarAplicacao, textoModuloFinanceiro, textoModuloAdministrativo, textoModuloFuncionario;
	private String textoModuloFornecedor, textoModuloCliente, textoModuloProduto, textoModuloTransporte, textoSobreAplicacao;
	
	/*Construtor da classe*/
	public AjudaTexto() {
		
	}
	
	public String getTextoNavegarAplicacao() {
		textoNavegarAplicacao = "Como navegar no software\r\n"
								+ "\r\n"
								+ "Acesso ao sistema:\r\n"
								+ "(1) Para acessar o sistema entre com os dados do login na tela de login (com a conta de administrador ou com "
								+ "os dados cadastrados no login(se o cadastro foi criado))\r\n"
								+ "\r\n"
								+ "Modulos do sistema (Presentes no menu do sistema):\r\n"
								+ "(1) Administrativo:\r\n"
								+ "---(1.1) Configurações:\r\n"
								+ "------(1.2.1) Dados da loja\r\n"
								+ "------(1.2.2) Ficha da loja\r\n"
								+ "---(1.2) Controle de Acesso\r\n"
								+ "(2) Cliente:\r\n"
								+ "---(2.1) Cadastro de Cliente\r\n"
								+ "---(2.2) Clientes\r\n"
								+ "(3) Financeiro\r\n"
								+ "---(3.1) Vendas\r\n"
								+ "------(3.2.1) Vendas\r\n"
								+ "------(3.1.2) Historico de Vendas\r\n"
								+ "------(3.1.3) Nota fiscal\r\n"
								+ "---(3.2) Compras:\r\n"
								+ "------(3.2.1) Compras\r\n"
								+ "------(3.2.2) Historico de Compras\r\n"
								+ "(4) Fornecedor\r\n"
								+ "---(4.1) Cadastro de Fornecedor\r\n"
								+ "---(4.2) Fornecedores\r\n"
								+ "(5) Funcionario\r\n"
								+ "---(5.1) Cadastro de Funcionario\r\n"
								+ "---(5.2) Funcionarios\r\n"
								+ "(6) Produtos\r\n"
								+ "---(6.1) Cadastro de Produto\r\n"
								+ "---(6.2) Estoque\r\n"
								+ "(7) Transporte\r\n"
								+ "---(7.1) Cadastro de Transporte\r\n"
								+ "---(7.2) Controle de carga\r\n"
								+ "(8) Ajuda\r\n"
								+ "\r\n"
								+ "Acesso a ficha do usuario logado\r\n"
								+ "(1) Ao lado do titulo da tela, no lado direito, esta localizado a parte da ficha do usuario que contem o nome, "
								+ "o cargo e o botao de aceeso a ficha com os dados do usuario logado, acessado por: gerente, atendente e carredor.\r\n";
		return textoNavegarAplicacao;
	}
	
	public String getTextoModuloFinanceiro() {
		textoModuloFinanceiro = "Modulo Financeiro: Parte do modulo finaceiro\r\n"
								+ "\r\n"
								+ "(1) Venda: Parte de vendas, acessado por: gerente e atendente.\r\n"
								+ "---(1.1) Venda: Onde a venda é realizada\r\n"
								+ "------(1.1.1) Inserir os dados do cliente no campo e apertar[Busca de cliente]:\r\n"
								+ "---------(a) Se o cliente for cadastrado, os dados vão aparecer na nota fiscal e no campo Codigo do Cliente.\r\n"
								+ "---------(b) Se o cliente não for cadastro:\r\n"
								+ "------------> Perguntar se o cliente quer ter um cadastro (Abre a tela de cadastro de cliente).\r\n"
								+ "------------> Perguntar se o cliente quer cadastrar od dados na nota fiscal (Abre a tela do cadastro dos dados do "
								+ "cliente na nota fiscal sem criar o cadastro no sistema).\r\n"
								+ "------------> Se o cliente não quiser um cadastro, os dados não aparecem na nota fiscal.\r\n"
								+ "------(1.1.2) Inserir a data e a hora da venda.\r\n"
								+ "------(1.1.3) Adicionar produto:\r\n"
								+ "---------(a) Apertar [Adicionar] para abrir a tela Adicionar produto\r\n"
								+ "------------> Preencher os campos.\r\n"
								+ "------------> Caso o nome, codigo do produto ou o codigo de barras seja conhecido digitar em um dos campos e apertar a tecla [Enter] "
								+ "para pesquisar, logo em seguida digitar o valor do desconto no campo porcentagem e confirmar os dados\r\n"
								+ "------------> Apos os dados do desconto serem adicionados, apertar [Confirmar]\r\n"
								+ "------(1.1.4) Remover produto:\r\n"
								+ "---------(a) Selecionar um produto e apertar [Remover] para remover o produto da lista.\r\n"
								+ "------(1.1.5) O botão [Limpar] limpa os campos\r\n"
								+ "------(1.1.6) Cancelar a venda:\r\n"
								+ "---------(a) Apertar [Cancelar] para cancelar a venda.\r\n"
								+ "------(1.1.7) Opções de pagamento:\r\n"
								+ "---------(a) Escolher o Tipo de Pagamento.\r\n"
								+ "---------(b) Escolher o Metodo de Pagamento:\r\n"
								+ "------------> A opção à vista abre a tela do desconto da compra, digitar o valor da porcentagem e confirmar.\r\n"
								+ "------------> A opção a prazo abre a tela das parcelas da compra, digitar o valor da porcentagem dos juros, "
								+ "a quantidade de parcelas e ao final confirmar os dados.\r\n"
								+ "------(1.1.8) Nota fiscal paulista: Perguntar se o cliente quer ou não a nota fiscal paulista\r\n"
								+ "------(1.1.9) Calculadora: Apertar [Calculadora] para abrir a calculadora.\r\n"
								+ "------(1.1.10) Ao final apertar [Finalizar] para finalizar a venda e gerar a Nota Fiscal.\r\n"
								+ "---(1.2) Historico de Venda: exibe as vendas realizadas, acessado por: gerente e atendente.\r\n"
								+ "------(1.2.1) Buscar os dados na tabela: digitar no campo e apertar [Buscar].\r\n"
								+ "------(1.2.2) Nota Fiscal\r\n"
								+ "---------(a) Apertar [Nota Fiscal]\r\n"
								+ "------------> Buscar os dados na tabela: digitar no campo e apertar [Buscar].\r\n"
								+ "------------> Selecionar um dado da nota fiscal na tabela e apertar [Exibir] para exibir os dados da nota fiscal.\r\n"
								+ "------------> O botão [Gerar nota fiscal] da ficha da nota fiscal gera a nota fiscal da venda.\r\n"
								+ "------------> O botão [Lista de produtos] da ficha da nota fiscal exibe a lista de produtos.\r\n"
								+ "------(1.2.3) Dados da venda\r\n"
								+ "---------(a) Selecionar um dado na tabela e apertar [Dados da venda] para exibir os dados da venda.\r\n"
								+ "------(1.2.4) Lista de produtos\r\n"
								+ "---------(a) Buscar os dados na tabela: digitar no campo e apertar [Buscar].\r\n"
								+ "---------(b) Selecionar um dado na tabela e apertar [Lista de produtos] para exibir a lista de produtos da venda.\r\n"
								+ "---------(c) Selecionar um produto na tabela e apertar [Exibir] para exibir a ficha do produto.\r\n"
								+ "(2) Compra: Parte da reposição de estoque, acessado por: gerente e atendente.\r\n"
								+ "---(2.1) Compra: Onde é registrada a perosição do estque.\r\n"
								+ "------(1.1.1) Opções de pagamento:\r\n"
								+ "---------(a) Escolher o Tipo de Pagamento.\r\n"
								+ "---------(b) Escolher o Metodo de Pagamento:\r\n"
								+ "------------> A opção à vista abre a tela do desconto da compra, digitar o valor da porcentagem e confirmar.\r\n"
								+ "------------> A opção a prazo abre a tela das parcelas da compra, digitar o valor da porcentagem dos juros, "
								+ "a quantidade de parcelas e ao final confirmar os dados.\r\n"
								+ "------(1.1.2) Inserir a data e a hora da venda.\r\n"
								+ "------(1.1.3) Adicionar produto:\r\n"
								+ "---------(a) Apertar [Adicionar] para abrir a tela Adicionar produto\r\n"
								+ "------------> Preencher os campos.\r\n"
								+ "------------> Caso o nome, codigo do produto ou o codigo de barras seja conhecido digitar em um dos campos e apertar a tecla [Enter] "
								+ "para pesquisar, logo em seguida digitar o valor do desconto no campo porcentagem e confirmar os dados\r\n"
								+ "------------> Apos os dados do desconto serem adicionados, apertar [Confirmar]\r\n"
								+ "------(1.1.4) Remover produto:\r\n"
								+ "---------(a) Selecionar um produto e apertar [Remover] para remover o produto da lista.\r\n"
								+ "------(1.1.5) O botão [Limpar] limpa os campos\r\n"
								+ "------(1.1.6) Cancelar a compra:\r\n"
								+ "---------(a) Apertar [Cancelar] para cancelar a compra.\r\n"
								+ "------(1.1.7) Nota fiscal paulista: Selecionar ou não se a nota fiscal paulista foi pedida.\r\n"
								+ "------(1.1.8) Calculadora: Apertar [Calculadora] para abrir a calculadora.\r\n"
								+ "------(1.1.9) Ao final apertar [Finalizar] para finalizar o registro da reposição do estoque.\r\n"
								+ "---(2.2) Historico de Compras: exibe as compras realizadas, acessado por: gerente e atendente.\r\n"
								+ "------(1.2.1) Buscar os dados na tabela: digitar no campo e apertar [Buscar].\r\n"
								+ "------(1.2.2) Dados da compra\r\n"
								+ "---------(a) Selecionar um dado na tabela e apertar [Dados da compra] para exibir os dados da compra.\r\n"
								+ "------(1.2.3) Lista de produtos\r\n"
								+ "---------(a) Buscar os dados na tabela: digitar no campo e apertar [Buscar].\r\n"
								+ "---------(b) Selecionar um dado na tabela e apertar [Lista de produtos] para exibir a lista de produtos da venda.\r\n"
								+ "---------(c) Selecionar um produto na tabela e apertar [Exibir] para exibir a ficha do produto.\r\n";
		return textoModuloFinanceiro;
	}
	
	public String getTextoModuloAdministrativo() {
		textoModuloAdministrativo = "Modulo Administrativo: Parte do modulo administrativo do sistema, acessado pelo gerente.\r\n"
									+ "\r\n"
									+ "(1) Configurações: parte onde os dados da loja são visualizados e cadastrados, acessado por: gerente.\r\n"
									+ "---(1.1) Campo com o estado dos dados da loja\r\n"
									+ "---------(a) Informa se os dados da loja foram registrados ou não forma registrados.\r\n"
									+ "---(1.2) Dados da loja: parte onde os dados da loja são cadastrados.\r\n"
									+ "------(1.2.1) Apertar [Dados da loja].\r\n"
									+ "------(1.2.2) Para cadastrar os dados da loja: inserir os dados nos campos e aperte o botão [salvar].\r\n"
									+ "---(1.3) Ficha da loja: parte onde os dados da loja são visualizados.\r\n"
									+ "------(1.3.1) Apertar [Ficha da loja]\r\n"
									+ "------(1.3.2) Para editar a ficha: apertar [editar], editar os dados da loja na ficha e apertar o botão [Salvar].\r\n"
									+ "(2) Controle de Acesso (Apenas se estar logado como gerente): exibe a data, a hora, o login e o nome de quem acessou o sistema, "
									+ "acessado por: gerente.\r\n"
									+ "---(2.1) Abrir a tela com a lista de acesso ao sistema (Controle de Acesso) (Apenas se estar logado como gerente)\r\n"
									+ "------(2.1.1) Buscar os dados na tabela: digitar no campo e apertar [Buscar].\r\n"
									+ "------(2.1.2) Ficha do Controle de Acesso\r\n"
									+ "---------(a) Para abrir a ficha: Selecionar um dado de acesso na tabela, apertar o botão [Ficha].\r\n"
									+ "---(2.2) Buscar os dados na tabela: digitar no campo e apertar [Buscar].\r\n";
		return textoModuloAdministrativo;
	}
	
	public String getTextoModuloFuncionario() {
		textoModuloFuncionario = "Modulo Funcionario: Parte do modulo funcionario do sistema.\r\n"
								+ "\r\n"
								+ "(1) Cadastro de funcionario: parte onde os dados do funcionario é cadastrado, acessado por: gerente\r\n"
								+ "---(1.1) Para cadastrar funcionários: inserir os dados nos campos e aperte o botão [salvar] (Apenas se estar logado como gerente).\r\n"
								+ "(2) Funcionarios: exibe os cadastros dos funcionarios, acessado por: gerente.\r\n"
								+ "---(2.1) Abrir a tela com os cadastros dos Funcionários (Tela Funcionários) (Apenas se estar logado como gerente)\r\n"
								+ "------(2.1.1) Buscar os dados na tabela: digitar no campo e apertar [Buscar].\r\n"
								+ "------(2.1.2) Ficha do Funcionário: Exibe os dados do funcionario, acessado por: gerente.\r\n"
								+ "---------(a) Para abrir a ficha: Selecionar um funcionário na tabela, apertar o botão [Ficha], para abrir a Ficha do Funcionário.\r\n"
								+ "---------(b) Para editar a ficha: apertar [editar], editar o cadastro do funcionário e apertar o botão [Salvar].\r\n"
								+ "---------(c) Aba do controle de férias/folgas na ficha do funcionario:\r\n"
								+ "------------> Adicionar férias/folgas: Apertar [Adicionar ferias/folga(s)], adicionar os dados e confirmar.\r\n"
								+ "------------> Buscar os dados na tabela: digitar no campo e apertar [Buscar].\r\n"
								+ "---------(d) Aba dos Dados Salariais:\r\n"
								+ "------------> Apertar [Adicionar] na parte de Aumento para adicionar um valor ao salário.\r\n"
								+ "------------> Apertar [Remover] na parte de Aumento para remover um valor de aumento ao salário.\r\n"
								+ "------------> Apertar [Adicionar] na parte de comissão/bônus para adicionar um valor de comissão/bônus ao salário.\r\n"
								+ "------------> Apertar [Remover] na parte de comissão/bônus para remover um um valor de comissão/bônus ao salário.\r\n"
								+ "------------> Buscar os dados na tabela: digitar no campo e apertar [Buscar].\r\n"
								+ "------(2.1.3) Na tela dos funcionários, selecionar um funcionário e abrir o controle de faltas.\r\n"
								+ "---------(a) Adicionar faltas/presenças na tela de Frequência do Funcionário.\r\n"
								+ "---------(b) Buscar os dados na tabela: digitar no campo e apertar [Buscar].\r\n"
								+ "---(2.2) Controle de faltas: parte de controle das faltas, acessado por: gerente.\r\n"
								+ "------(2.2.1) Na tela dos cadastros dos funcionarios selecionar um funcionario e apertar [Controle de faltas].\r\n"
								+ "------(2.2.2) Adicionar frequencia: apertar [Frequencia], escolher entre as opções Presença e Falta e confirmar.\r\n"
								+ "------(2.2.3) Buscar os dados na tabela: digitar no campo e apertar [Buscar].\r\n"
								+ "---(2.3) Apertar [Atualizar tabela] par atualizar a tabela com os cadastros dos Funcionários.\r\n";
		return textoModuloFuncionario;
	}
	
	public String getTextoModuloFornecedor() {
		textoModuloFornecedor = "Modulo Fornecedor: Parte dos modulos administrativos do sistema.\r\n"
								+ "\r\n"
								+ "(1) Cadastro de Fornecedor: parte onde os dados do fornecedor é cadastrado, acessado por: gerente e atendente.\r\n"
								+ "---(1.1) Para cadastrar fornecedores: inserir os dados nos campos e aperte o botão [salvar].\r\n"
								+ "(2) Fornecedores: exibe os cadastros dos fornecedores, acessado por: gerente e atendente.\r\n"
								+ "---(2.1) Abrir a tela com os cadastros dos Fornecedores (Tela Fornecedores)\r\n"
								+ "------(2.1.1) Buscar os dados na tabela: digitar no campo e apertar [Buscar].\r\n"
								+ "------(2.1.2) Ficha do Fornecedor: exibe os dados do fornecedor, acessado por: gerente e atendente.\r\n"
								+ "---------(a) Para abrir a ficha: Selecionar um fornecedor na tabela, apertar o botão [Ficha].\r\n"
								+ "---------(b) Para editar a ficha: apertar [editar], editar o cadastro do fornecedor e apertar o botão [Salvar].\r\n"
								+ "---------(a) Aba Produtos relacionados na ficha do fornecedor:\r\n"
								+ "------------> Buscar os dados na tabela: digitar no campo e apertar [Buscar].\r\n"
								+ "------------> Ficha dos produtos: Selecionar um produto na tabela e apertar [Ficha do produto]\r\n"
								+ "---------(b) Aba do Historico de Compras com este fornecedor na ficha do funcionario:\r\n"
								+ "---(2.2) Buscar os dados na tabela: digitar no campo e apertar [Buscar].\r\n"
								+ "---(2.3) Apertar [Atualizar tabela] par atualizar a tabela com os cadastros dos Fornecedores.\r\n";
		return textoModuloFornecedor;
	}
	
	public String getTextoModuloCliente() {
		textoModuloCliente = "Modulo Cliente: Parte do modulo do cliente.\r\n"
							+ "\r\n"
							+ "(1) Cadastro de cliente: parte onde os dados do cliente é cadastrado, acessado por: gerente e atendente.\r\n"
							+ "---(1.1) Para cadastrar funcionários: inserir os dados nos campos e aperte o botão [salvar].\r\n"
							+ "(2) Clientes: exibe os cadastros dos clientes, acessado por: gerente, atendente e carredor.\r\n"
							+ "---(2.1) Abrir a tela com os cadastros dos Clientes (Tela Funcionários) (Apenas se estar logado como gerente e atendente)\r\n"
							+ "------(2.1.1) Buscar os dados na tabela: digitar no campo e apertar [Buscar].\r\n"
							+ "------(2.1.2) Ficha do Cliente: exibe os dados do cliente, acessado por: gerente, atendente e carregador.\r\n"
							+ "---------(a) Para abrir a ficha: Selecionar um cliente na tabela, apertar o botão [Ficha].\r\n"
							+ "---------(b) Para editar a ficha: apertar [editar], editar o cadastro do cliente e apertar o botão [Salvar].\r\n"
							+ "---------(c) Aba do historico de compras:\r\n"
							+ "------------> Buscar os dados na tabela: digitar no campo e apertar [Buscar].\r\n"
							+ "---(2.2) Buscar os dados na tabela: digitar no campo e apertar [Buscar].\r\n"
							+ "---(2.3) Apertar [Atualizar tabela] para atualizar a tabela com os cadastros dos Clientes.\r\n";
		return textoModuloCliente;
	}
	
	public String getTextoModuloProduto() {
		textoModuloProduto = "Modulo Produto: Parte do modulo do produto.\r\n"
							+ "\r\n"
							+ "(1) Cadastro de produto: parte onde os dados do produto é cadastrado, acessado por: gerente, atendente e carredor.\r\n"
							+ "---(1.1) Para cadastrar produtos: inserir os dados nos campos e aperte o botão [salvar].\r\n"
							+ "(2) Estoque: exibe os cadastros dos produtos, acessado por: gerente, atendente e carredor.\r\n"
							+ "---(2.1) Abrir a tela com os cadastros dos produtos (Tela Estoque).\r\n"
							+ "------(2.1.1) Buscar os dados na tabela: digitar no campo e apertar [Buscar].\r\n"
							+ "------(2.1.2) Ficha do Funcionário: exibe o cadastro do produto, acessado por: gerente, atendente e carredor\r\n"
							+ "---------(a) Para abrir a ficha: Selecionar um produto na tabela, apertar o botão [Ficha].\r\n"
							+ "---------(b) Para editar a ficha: apertar [editar], editar o cadastro do produto e apertar o botão [Salvar], acessado por: gerente. atendente.\r\n"
							+ "---------(c) Aba Acessorios: Exibe os dados da descrição\r\n"
							+ "---------(d) Aba Descrição: Exibe os acessorios do produto\r\n"
							+ "---(2.2) Buscar os dados na tabela: digitar no campo e apertar [Buscar].\r\n"
							+ "---(2.3) Apertar [Atualizar tabela] par atualizar a tabela com os cadastros dos produtos.\r\n"
							+ "(3) Descontos e Promoções: parte exibe os cadastros dos produtos, acessado por: gerente e atendente.\r\n"
							+ "---(3.1) Aba Promoção\r\n"
							+ "------(3.1.1) Criar promoção: aperte [Adicionar Promoção].\r\n"
							+ "---------(a) Preencher os campos, escolher o responsavel atraves do botao [Responsavel] e a descrição da promoção.\r\n"
							+ "---------(b) Para adicionar produtos:\r\n"
							+ "------------> Apertar [Adicionar] que abre a tela Adicionar Produto, preencha os campos e confirme os dados.\r\n"
							+ "------------> Caso o nome, codigo do produto ou o codigo de barras seja conhecido digitar em um dos campos e apertar a tecla [Enter] "
							+ "para pesquisar, logo em seguida digitar o valor do desconto no campo porcentagem e confirmar os dados.\r\n"
							+ "---------(c) Para remover produtos: Selecionar um produto e apertar [Remover] para remover o produto da lista.\r\n"
							+ "---------(d) Apos os dados da promoção serem adicionados, apertar [Salvar]\r\n"
							+ "------(3.1.2) Buscar os dados na tabela: digitar no campo e apertar [Buscar].\r\n"
							+ "------(3.1.3) Ficha com os dados da promoção:\r\n"
							+ "---------(a) Selecionar um dado da tabela e apertar [Ficha].\r\n"
							+ "---------(b) Lista de produtos:\r\n"
							+ "------------> Apertar [Exibir lista de produtos].\r\n"
							+ "------------> Ficha dos produtos: Apertar [Ficha do produto]\r\n"
							+ "------------> Buscar os dados na tabela: digitar no campo e apertar [Buscar].\r\n"
							+ "---------(c)	Cancelar a promoção: Apertar [Cancelar promoção]\r\n"
							+ "---(3.2) Aba Desconto\r\n"
							+ "------(3.2.1) Criar desconto: aperte [Adicionar Desconto].\r\n"
							+ "---------(a) Para adicionar produtos:\r\n"
							+ "------------> Preencher os campos.\r\n"
							+ "------------> Escolher o responsavel atraves do botao [Responsavel].\r\n"
							+ "------------> Caso o nome, codigo do produto ou o codigo de barras seja conhecido digitar em um dos campos e apertar a tecla [Enter] "
							+ "para pesquisar, logo em seguida digitar o valor do desconto no campo porcentagem e confirmar os dados\r\n"
							+ "------------> Apos os dados do desconto serem adicionados, apertar [Salvar]\r\n"
							+ "------(3.1.3) Ficha com os dados do desconto:\r\n"
							+ "---------(a) Selecionar um dado da tabela e apertar [Ficha].\r\n"
							+ "---------(b)	Cancelar o desconto: Apertar [Cancelar desconto]\r\n"
							+ "------(3.2.3) Buscar os dados na tabela: digitar no campo e apertar [Buscar].\r\n"
							+ "---(3.3) Apertar [Atualizar] para atualizar as tabelas das promoções e dos descontos.\r\n";
		return textoModuloProduto;
	}

	public String getTextoModuloTransporte() {
		textoModuloTransporte = "Modulo Transporte: Parte do modulo de transporte.\r\n"
								+ "\r\n"
								+ "(1) Cadastro de Transporte: parte onde os dados do transporte é cadastrado, acessado por: gerente, atendente e carredor.\r\n"
								+ "---(1.1) Para cadastrar o transporte da carga: inserir os dados nos campos e aperte o botão [salvar].\r\n"
								+ "(2) Controle de Cargas: exibe os cadastros das cargas, acessado por: gerente, atendente e carredor.\r\n"
								+ "---(2.1) Abrir a tela com os cadastros das cargas (Controle de Cargas).\r\n"
								+ "------(2.1.1) Buscar os dados na tabela: digitar no campo e apertar [Buscar].\r\n"
								+ "------(2.1.2) Ficha do Cadastro de transporte de cargas, acessado por: gerente, atendente e carredor.\r\n"
								+ "---------(a) Para abrir a ficha: Selecionar um dado na tabela, apertar o botão [Ficha].\r\n"
								+ "---------(b) Para editar a ficha: apertar [editar], editar o cadastro da carga e apertar o botão [Salvar].\r\n"
								+ "---(2.2) Buscar os dados na tabela: digitar no campo e apertar [Buscar].\r\n"
								+ "---(2.3) Apertar [Atualizar tabela] para atualizar a tabela do controle de cargas.\r\n";
		return textoModuloTransporte;
	}

	public String getTextoSobreAplicacao() {
		textoSobreAplicacao = "Sobre o software\r\n"
							+ "\r\n"
							+ "Edição de imagens: Otavio Henrique \r\n"
							+ "Engenharia de Software: Otavio Henrique \r\n"
							+ "Programador: Otavio Henrique \r\n"
							+ "Testes: Otavio Henrique \r\n";
		return textoSobreAplicacao;
	}
}